# Generated by Django 3.2.12 on 2022-11-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0002_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='name',
        ),
        migrations.AlterModelTable(
            name='oferta',
            table='oferta',
        ),
    ]
